baseurl = "http://jrutheiser.com/"
languageCode = "en-us"
title = "Lithium Theme"
theme = "hugo-lithium-theme"
googleAnalytics = "UA-77448120-1"

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/jrutheiser"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/jrutheiser"

[params]
    [params.logo]
    url = "logo.png"
    width = 50
    height = 50

